### ISSUE TITLE
Link to feed is not available when no groups have been configured

### ISSUE THREAD

**Issue by seanmadsen** [twomice/com.joineryhq.activityical#16]
Steps to reproduce: 

1. Install extension
1. Do not edit any extensions configuration
1. Go to a contact with assigned activities in the future
1. Expect to see a link to the feed in the contact's activities tab
1. Observe that the activities tab does not have any links to iCal feeds

**Comment by seanmadsen** [comment]
Note: when you configure this extension to use a group, then this bug is not reproducible

**Comment by twomice** [comment]
This is by design and documented in the README under "Installation and Configuration".  I'm inclined to leave it as-is, but am open to suggestions on making it less mysterious.

**Comment by seanmadsen** [comment]
Ahh, yes. Re-reading I agree with you @twomice. Documentation is definitely sufficient to make this point clear. (Sorry, I wrote this ticket in a bit of a hurry and during our call yesterday)
