### ISSUE TITLE
Populate settings with "yes" or "no" after installation

### ISSUE THREAD

**Issue by seancolsen** [twomice/com.joineryhq.activityical#19]
After a fresh install of this extension, I go to the extension's settings page and see the following

![screenshot26](https://cloud.githubusercontent.com/assets/42411/25056505/926ce0c2-2126-11e7-82c5-e6fa1e0e9af8.png)

I think it would be nice if one of the options, either "yes" or "no" were already filled out for each of these settings, so that it's clear to the user how the extension will behave by default

**Comment by twomice** [comment]
Fixed in master on 4a1916c. Thanks for the suggestion (and patience) @seancolsen !
