### ISSUE TITLE
API Failing - not able to view activities from Contact Summary Page

### ISSUE THREAD

**Issue by JVeitia** [twomice/com.joineryhq.activityical#22]
Starting with Civi 5.4.1, I was getting a Network Error when attempting to view the Activities tab from the contact summary.  I UL backtrace in this snippet https://lab.civicrm.org/snippets/6?expanded=true&viewer=simple  (sorry for the large size of the file)

**Comment by MikeyMJCO** [comment]
Here are the relevant parts of the log:

`Sep 13 09:48:24  [info] 
$Fatal Error Details = array(3) {
  ["message"]=>
  string(45) "'24' is not a valid option for field group_id"
  ["code"]=>
  NULL
  ["exception"]=>
  object(CiviCRM_API3_Exception)#497 (8) {
    ["extraParams":"CiviCRM_API3_Exception":private]=>
    array(6) {
      ["error_field"]=>
      string(8) "group_id"
      ["error_code"]=>
      int(2001)
      ["entity"]=>
      string(12) "GroupContact"
      ["action"]=>
      string(3) "get"
      ["is_error"]=>
      int(1)
      ["error_message"]=>
      string(45) "'24' is not a valid option for field group_id"
    }
    ["message":protected]=>
    string(45) "'24' is not a valid option for field group_id"
    ["string":"Exception":private]=>
    string(0) ""
    ["code":protected]=>
    int(0)
    ["file":protected]=>
    string(70) "/home/lofcenter/www/www/wp-content/plugins/civicrm/civicrm/api/api.php"
    ["line":protected]=>
    int(45)
    ["trace":"Exception":private]=>
    array(22) {
      [0]=>
      array(4) {
        ["file"]=>
        string(98) "/home/lofcenter/www/www/wp-content/uploads/civicrm/ext/com.joineryhq.activityical/activityical.php"
        ["line"]=>
        int(246)
        ["function"]=>
        string(12) "civicrm_api3"
        ["args"]=>
        array(3) {
          [0]=>
          string(13) "group_contact"
          [1]=>
          string(3) "get"
          [2]=>
          array(3) {
            ["group_id"]=>
            string(2) "24"
            ["contact_id"]=>
            string(4) "5633"
            ["version"]=>
            int(3)
          }
        }
      }
      [1]=>
      array(4) {
        ["file"]=>
        string(98) "/home/lofcenter/www/www/wp-content/uploads/civicrm/ext/com.joineryhq.activityical/activityical.php"
        ["line"]=>
        int(191)
        ["function"]=>
        string(36) "_activityical_contact_has_feed_group"
        ["args"]=>
        array(1) {
          [0]=>
          string(4) "5633"
        }
      }
      [2]=>
      array(4) {
        ["file"]=>
        string(77) "/home/lofcenter/www/www/wp-content/plugins/civicrm/civicrm/CRM/Utils/Hook.php"
        ["line"]=>
        int(270)
        ["function"]=>
        string(28) "activityical_civicrm_pageRun"
        ["args"]=>
        array(1) {
          [0]=>
          &object(CRM_Activity_Page_Tab)#553 (12) {
            ["_name":protected]=>
            string(21) "CRM_Activity_Page_Tab"
            ["_title":protected]=>
            string(10) "Activities"
            ["_mode":protected]=>
            string(4) "null"
            ["_embedded":protected]=>
            bool(false)
            ["_print":protected]=>
            string(4) "json"
            ["ajaxResponse"]=>
            array(1) {
              ["tabCount"]=>
              string(1) "2"
            }
            ["urlPath"]=>
            array(4) {
              [0]=>
              string(7) "civicrm"
              [1]=>
              string(7) "contact"
              [2]=>
              string(4) "view"
              [3]=>
              string(8) "activity"
            }
            ["useLivePageJS"]=>
            NULL
            ["_id"]=>
            NULL
            ["_contactId"]=>
            string(4) "5633"
            ["_permission"]=>
            int(1)
            ["_action"]=>
            int(16)
          }
        }
      }
      [3]=>
      array(6) {
        ["file"]=>
        string(87) "/home/lofcenter/www/www/wp-content/plugins/civicrm/civicrm/CRM/Utils/Hook/WordPress.php"
        ["line"]=>
        int(155)
        ["function"]=>
        string(8) "runHooks"
        ["class"]=>
        string(14) "CRM_Utils_Hook"
        ["type"]=>
        string(2) "->"
        ["args"]=>
        array(9) {
          [0]=>
          array(7) {
            [0]=>
            string(9) "wordpress"
            ["mappins"]=>
            string(7) "mappins"
            ["extendedreport"]=>
            string(14) "extendedreport"
            ["civisualize"]=>
            string(11) "civisualize"
            ["uscounties"]=>
            string(10) "uscounties"
            ["activityical"]=>
            string(12) "activityical"
            ["casetokens"]=>
            string(10) "casetokens"
          }
          [1]=>
          string(15) "civicrm_pageRun"
          [2]=>
          int(1)
          [3]=>
          &object(CRM_Activity_Page_Tab)#553 (12) {
            ["_name":protected]=>
            string(21) "CRM_Activity_Page_Tab"
            ["_title":protected]=>
            string(10) "Activities"
            ["_mode":protected]=>
            string(4) "null"
            ["_embedded":protected]=>
            bool(false)
            ["_print":protected]=>
            string(4) "json"
            ["ajaxResponse"]=>
            array(1) {
              ["tabCount"]=>
              string(1) "2"
            }
            ["urlPath"]=>
            array(4) {
              [0]=>
              string(7) "civicrm"
              [1]=>
              string(7) "contact"
              [2]=>
              string(4) "view"
              [3]=>
              string(8) "activity"
            }
            ["useLivePageJS"]=>
            NULL
            ["_id"]=>
            NULL
            ["_contactId"]=>
            string(4) "5633"
            ["_permission"]=>
            int(1)
            ["_action"]=>
            int(16)
          }
          [4]=>
          &NULL
          [5]=>
          &NULL
          [6]=>
          &NULL
          [7]=>
          &NULL
          [8]=>
          &NULL
        }
      }
      [4]=>
      array(6) {
        ["file"]=>
        string(92) "/home/lofcenter/www/www/wp-content/plugins/civicrm/civicrm/Civi/Core/CiviEventDispatcher.php"
        ["line"]=>
        int(86)
        ["function"]=>
        string(11) "invokeViaUF"
        ["class"]=>
        string(24) "CRM_Utils_Hook_WordPress"
        ["type"]=>
        string(2) "->"
        ["args"]=>
        array(8) {
          [0]=>
          int(1)
          [1]=>
          &object(CRM_Activity_Page_Tab)#553 (12) {
            ["_name":protected]=>
            string(21) "CRM_Activity_Page_Tab"
            ["_title":protected]=>
            string(10) "Activities"
            ["_mode":protected]=>
            string(4) "null"
            ["_embedded":protected]=>
            bool(false)
            ["_print":protected]=>
            string(4) "json"
            ["ajaxResponse"]=>
            array(1) {
              ["tabCount"]=>
              string(1) "2"
            }
            ["urlPath"]=>
            array(4) {
              [0]=>
              string(7) "civicrm"
              [1]=>
              string(7) "contact"
              [2]=>
              string(4) "view"
              [3]=>
              string(8) "activity"
            }
            ["useLivePageJS"]=>
            NULL
            ["_id"]=>
            NULL
            ["_contactId"]=>
            string(4) "5633"
            ["_permission"]=>
            int(1)
            ["_action"]=>
            int(16)
          }
          [2]=>
          &NULL
          [3]=>
          &NULL
          [4]=>
          &NULL
          [5]=>
          &NULL
          [6]=>
          &NULL
          [7]=>
          string(15) "civicrm_pageRun"
        }
      }
      [5]=>
      array(4) {
        ["function"]=>
        string(12) "delegateToUF"
        ["class"]=>
        string(29) "Civi\Core\CiviEventDispatcher"
        ["type"]=>
        string(2) "::"
        ["args"]=>
        array(3) {
          [0]=>
          object(Civi\Core\Event\GenericHookEvent)#498 (7) {
            ["hookValues":protected]=>
            array(1) {
              [0]=>
              &object(CRM_Activity_Page_Tab)#553 (12) {
                ["_name":protected]=>
                string(21) "CRM_Activity_Page_Tab"
                ["_title":protected]=>
                string(10) "Activities"
                ["_mode":protected]=>
                string(4) "null"
                ["_embedded":protected]=>
                bool(false)
                ["_print":protected]=>
                string(4) "json"
                ["ajaxResponse"]=>
                array(1) {
                  ["tabCount"]=>
                  string(1) "2"
                }
                ["urlPath"]=>
                array(4) {
                  [0]=>
                  string(7) "civicrm"
                  [1]=>
                  string(7) "contact"
                  [2]=>
                  string(4) "view"
                  [3]=>
                  string(8) "activity"
                }
                ["useLivePageJS"]=>
                NULL
                ["_id"]=>
                NULL
                ["_contactId"]=>
                string(4) "5633"
                ["_permission"]=>
                int(1)
                ["_action"]=>
                int(16)
              }
            }
            ["hookFields":protected]=>
            array(1) {
              [0]=>
              string(4) "page"
            }
            ["hookFieldsFlip":protected]=>
            array(1) {
              ["page"]=>
              int(0)
            }
            ["returnValues":"Civi\Core\Event\GenericHookEvent":private]=>
            array(0) {
            }
            ["propagationStopped":"Symfony\Component\EventDispatcher\Event":private]=>
            bool(false)
            ["dispatcher":"Symfony\Component\EventDispatcher\Event":private]=>
            object(Civi\Core\CiviEventDispatcher)#1924 (6) {
              ["autoListeners":"Civi\Core\CiviEventDispatcher":private]=>
              array(18) {
                ["hook_civicrm_config"]=>
                int(1)
                ["hook_civicrm_optionValues"]=>
                int(1)
                ["hook_civicrm_fieldOptions"]=>
                int(1)
                ["civi.api.resolve"]=>
                int(1)
                ["civi.api.authorize"]=>
                int(1)
                ["civi.api.prepare"]=>
                int(1)
                ["hook_civicrm_apiWrappers"]=>
                int(1)
                ["civi.api.respond"]=>
                int(1)
                ["hook_civicrm_contact_get_displayname"]=>
                int(1)
                ["hook_civicrm_recent"]=>
                int(1)
                ["hook_civicrm_permission_check"]=>
                int(1)
                ["hook_civicrm_preProcess"]=>
                int(1)
                ["hook_civicrm_buildForm"]=>
                int(1)
                ["hook_civicrm_alterTemplateFile"]=>
                int(1)
                ["hook_civicrm_pageRun"]=>
                int(1)
                ["hook_civicrm_alterSettingsMetaData"]=>
                int(1)
                ["civi.api.exception"]=>
                int(1)
                ["hook_civicrm_unhandled_exception"]=>
                int(1)
              }
              ["container":"Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher":private]=>
              object(CachedCiviContainer)#1921 (12) {
                ["parameters":"CachedCiviContainer":private]=>
                array(1) {
                  ["civicrm_base_path"]=>
                  string(58) "/home/lofcenter/www/www/wp-content/plugins/civicrm/civicrm"
                }
                ["targetDirs":"CachedCiviContainer":private]=>
                array(0) {
                }
                ["parameterBag":protected]=>
                NULL
                ["services":protected]=>
                array(13) {
                  ["runtime"]=>
                  object(CRM_Core_Config_Runtime)#1980 (17) {
                    ["dsn"]=>
                    string(77) "mysql://lofcenter:uLyTZStJ@127.0.0.1/lofcenter_suresupport_test?new_link=true"
                    ["userFramework"]=>
                    string(9) "WordPress"
                    ["userFrameworkBaseURL"]=>
                    NULL
                    ["userFrameworkClass"]=>
                    string(26) "CRM_Utils_System_WordPress"
                    ["userFrameworkDSN"]=>
                    string(69) "mysql://lofcenter:uLyTZStJ@127.0.0.1/lofcenter_stage_wp?new_link=true"
                    ["userFrameworkURLVar"]=>
                    string(1) "q"
                    ["userFrameworkVersion"]=>
                    NULL
                    ["useFrameworkRelativeBase"]=>
                    NULL
                    ["userHookClass"]=>
                    string(24) "CRM_Utils_Hook_WordPress"
                    ["cleanURL"]=>
                    int(0)
                    ["configAndLogDir"]=>
                    string(64) "/home/lofcenter/www/www/wp-content/uploads/civicrm/ConfigAndLog/"
                    ["templateCompileDir"]=>
                    string(63) "/home/lofcenter/www/www/wp-content/uploads/civicrm/templates_c/"
                    ["templateDir"]=>
                    array(1) {
                      [0]=>
                      string(69) "/home/lofcenter/www/www/wp-content/plugins/civicrm/civicrm/templates/"
                    }
                    ["map":"CRM_Core_Config_MagicMerge":private]=>
                    array(97) {
                      ["doNotResetCache"]=>
                      array(1) {
                        [0]=>
                        string(5) "local"
                      }
                      ["inCiviCRM"]=>
                      array(1) {
                        [0]=>
                        string(5) "local"
                      }
                      ["keyDisable"]=>
                      array(1) {
                        [0]=>
                        string(5) "local"
                      }
                      ["userFrameworkFrontend"]=>
                      array(1) {
                        [0]=>
                        string(5) "local"
                      }
                      ["userPermissionTemp"]=>
                      array(1) {
                        [0]=>
                        string(5) "local"
                      }
                      ["dsn"]=>
                      array(1) {
                        [0]=>
                        string(7) "runtime"
                      }
                      ["initialized"]=>
                      array(1) {
                        [0]=>
                        string(7) "runtime"
                      }
                      ["userFramework"]=>
                      array(1) {
                        [0]=>
                        string(7) "runtime"
                      }
                      ["userFrameworkClass"]=>
                      array(1) {
                        [0]=>
                        string(7) "runtime"
                      }
                      ["userFrameworkDSN"]=>
                      array(1) {
                        [0]=>
                        string(7) "runtime"
                      }
                      ["userFrameworkURLVar"]=>
                      array(1) {
                        [0]=>
                        string(7) "runtime"
                      }
                      ["userHookClass"]=>
                      array(1) {
                        [0]=>
                        string(7) "runtime"
                      }
                      ["cleanURL"]=>
                      array(1) {
                        [0]=>
                        string(7) "runtime"
                      }
                      ["configAndLogDir"]=>
                      array(1) {
                        [0]=>
                        string(7) "runtime"
                      }
                      ["templateCompileDir"]=>
                      array(1) {
                        [0]=>
                        string(7) "runtime"
                      }
                      ["templateDir"]=>
                      array(1) {
                        [0]=>
                        string(7) "runtime"
                      }
                      ["userSystem"]=>
                      array(1) {
                        [0]=>
                        string(8) "boot-svc"
                      }
                      ["userPermissionClass"]=>
                      array(1) {
                        [0]=>
                        string(8) "boot-svc"
                      }
                      ["userFrameworkBaseURL"]=>
                      array(2) {
                        [0]=>
                        string(11) "user-system"
                        [1]=>
                        string(18) "getAbsoluteBaseURL"
                      }
                      ["userFrameworkVersion"]=>
                      array(2) {
                        [0]=>
                        string(11) "user-system"
                        [1]=>
                        string(10) "getVersion"
                      }
                      ["useFrameworkRelativeBase"]=>
                      array(2) {
                        [0]=>
                        string(11) "user-system"
                        [1]=>
                        string(18) "getRelativeBaseURL"
                      }
                      ["backtrace"]=>
                      array(1) {
                        [0]=>
                        string(7) "setting"
                      }
                      ["contact_default_language"]=>
                      array(1) {
                        [0]=>
                        string(7) "setting"
                      }
                      ["countryLimit"]=>
                      array(1) {
                        [0]=>
                        string(7) "setting"
                      }
                      ["customTranslateFunction"]=>
                      array(1) {
                        [0]=>
                        string(7) "setting"
                      }
                      ["dateInputFormat"]=>
                      array(1) {
                        [0]=>
                        string(7) "setting"
                      }
                      ["dateformatDatetime"]=>
                      array(1) {
                        [0]=>
                        string(7) "setting"
                      }
                      ["dateformatFull"]=>
                      array(1) {
                        [0]=>
                        string(7) "setting"
                      }
                      ["dateformatPartial"]=>
                      array(1) {
                        [0]=>
                        string(7) "setting"
                      }
                      ["dateformatTime"]=>
                      array(1) {
                        [0]=>
                        string(7) "setting"
                      }
                      ["dateformatYear"]=>
                      array(1) {
                        [0]=>
                        string(7) "setting"
                      }
                      ["dateformatFinancialBatch"]=>
                      array(1) {
                        [0]=>
                        string(7) "setting"
                      }
                      ["dateformatshortdate"]=>
                      array(1) {
                        [0]=>
                        string(7) "setting"
                      }
                      ["debug"]=>
                      array(2) {
                        [0]=>
                        string(7) "setting"
                        [1]=>
                        string(13) "debug_enabled"
                      }
                      ["defaultContactCountry"]=>
                      array(1) {
                        [0]=>
                        string(7) "setting"
                      }
                      ["defaultContactStateProvince"]=>
                      array(1) {
                        [0]=>
                        string(7) "setting"
                      }
                      ["defaultCurrency"]=>
                      array(1) {
                        [0]=>
                        string(7) "setting"
                      }
                      ["defaultSearchProfileID"]=>
                      array(1) {
                        [0]=>
                        string(7) "setting"
                      }
                      ["doNotAttachPDFReceipt"]=>
                      array(1) {
                        [0]=>
                        string(7) "setting"
                      }
                      ["empoweredBy"]=>
                      array(1) {
                        [0]=>
                        string(7) "setting"
                      }
                      ["enableComponents"]=>
                      array(2) {
                        [0]=>
                        string(7) "setting"
                        [1]=>
                        string(17) "enable_components"
                      }
                      ["enableSSL"]=>
                      array(1) {
                        [0]=>
                        string(7) "setting"
                      }
                      ["fatalErrorHandler"]=>
                      array(1) {
                        [0]=>
                        string(7) "setting"
                      }
                      ["fieldSeparator"]=>
                      array(1) {
                        [0]=>
                        string(7) "setting"
                      }
                      ["fiscalYearStart"]=>
                      array(1) {
                        [0]=>
                        string(7) "setting"
                      }
                      ["geoAPIKey"]=>
                      array(1) {
                        [0]=>
                        string(7) "setting"
                      }
                      ["geoProvider"]=>
                      array(1) {
                        [0]=>
                        string(7) "setting"
                      }
                      ["includeAlphabeticalPager"]=>
                      array(1) {
                        [0]=>
                        string(7) "setting"
                      }
                      ["includeEmailInName"]=>
                      array(1) {
                        [0]=>
                        string(7) "setting"
                      }
                      ["includeNickNameInName"]=>
                      array(1) {
                        [0]=>
                        string(7) "setting"
                      }
                      ["includeOrderByClause"]=>
                      array(1) {
                        [0]=>
                        string(7) "setting"
                      }
                      ["includeWildCardInName"]=>
                      array(1) {
                        [0]=>
                        string(7) "setting"
                      }
                      ["inheritLocale"]=>
                      array(1) {
                        [0]=>
                        string(7) "setting"
                      }
                      ["languageLimit"]=>
                      array(1) {
                        [0]=>
                        string(7) "setting"
                      }
                      ["lcMessages"]=>
                      array(1) {
                        [0]=>
                        string(7) "setting"
                      }
                      ["legacyEncoding"]=>
                      array(1) {
                        [0]=>
                        string(7) "setting"
                      }
                      ["logging"]=>
                      array(1) {
                        [0]=>
                        string(7) "setting"
                      }
                      ["mailThrottleTime"]=>
                      array(1) {
                        [0]=>
                        string(7) "setting"
                      }
                      ["mailerBatchLimit"]=>
                      array(1) {
                        [0]=>
                        string(7) "setting"
                      }
                      ["mailerJobSize"]=>
                      array(1) {
                        [0]=>
                        string(7) "setting"
                      }
                      ["mailerJobsMax"]=>
                      array(1) {
                        [0]=>
                        string(7) "setting"
                      }
                      ["mapAPIKey"]=>
                      array(1) {
                        [0]=>
                        string(7) "setting"
                      }
                      ["mapProvider"]=>
                      array(1) {
                        [0]=>
                        string(7) "setting"
                      }
                      ["maxFileSize"]=>
                      array(1) {
                        [0]=>
                        string(7) "setting"
                      }
                      ["maxAttachments"]=>
                      array(2) {
                        [0]=>
                        string(7) "setting"
                        [1]=>
                        string(15) "max_attachments"
                      }
                      ["monetaryDecimalPoint"]=>
                      array(1) {
                        [0]=>
                        string(7) "setting"
                      }
                      ["monetaryThousandSeparator"]=>
                      array(1) {
                        [0]=>
                        string(7) "setting"
                      }
                      ["moneyformat"]=>
                      array(1) {
                        [0]=>
                        string(7) "setting"
                      }
                      ["moneyvalueformat"]=>
                      array(1) {
                        [0]=>
                        string(7) "setting"
                      }
                      ["provinceLimit"]=>
                      array(1) {
                        [0]=>
                        string(7) "setting"
                      }
                      ["recaptchaOptions"]=>
                      array(1) {
                        [0]=>
                        string(7) "setting"
                      }
                      ["recaptchaPublicKey"]=>
                      array(1) {
                        [0]=>
                        string(7) "setting"
                      }
                      ["recaptchaPrivateKey"]=>
                      array(1) {
                        [0]=>
                        string(7) "setting"
                      }
                      ["forceRecaptcha"]=>
                      array(1) {
                        [0]=>
                        string(7) "setting"
                      }
                      ["replyTo"]=>
                      array(1) {
                        [0]=>
                        string(7) "setting"
                      }
                      ["secondDegRelPermissions"]=>
                      array(1) {
                        [0]=>
                        string(7) "setting"
                      }
                      ["smartGroupCacheTimeout"]=>
                      array(1) {
                        [0]=>
                        string(7) "setting"
                      }
                      ["timeInputFormat"]=>
                      array(1) {
                        [0]=>
                        string(7) "setting"
                      }
                      ["userFrameworkLogging"]=>
                      array(1) {
                        [0]=>
                        string(7) "setting"
                      }
                      ["userFrameworkUsersTableName"]=>
                      array(1) {
                        [0]=>
                        string(7) "setting"
                      }
                      ["verpSeparator"]=>
                      array(1) {
                        [0]=>
                        string(7) "setting"
                      }
                      ["wkhtmltopdfPath"]=>
                      array(1) {
                        [0]=>
                        string(7) "setting"
                      }
                      ["wpBasePage"]=>
                      array(1) {
                        [0]=>
                        string(7) "setting"
                      }
                      ["wpLoadPhp"]=>
                      array(1) {
                        [0]=>
                        string(7) "setting"
                      }
                      ["customFileUploadDir"]=>
                      array(3) {
                        [0]=>
                        string(12) "setting-path"
                        [1]=>
                        NULL
                        [2]=>
                        array(2) {
                          [0]=>
                          string(5) "mkdir"
                          [1]=>
                          string(8) "restrict"
                        }
                      }
                      ["customPHPPathDir"]=>
                      array(1) {
                        [0]=>
                        string(12) "setting-path"
                      }
                      ["customTemplateDir"]=>
                      array(1) {
                        [0]=>
                        string(12) "setting-path"
                      }
                      ["extensionsDir"]=>
                      array(3) {
                        [0]=>
                        string(12) "setting-path"
                        [1]=>
                        NULL
                        [2]=>
                        array(1) {
                          [0]=>
                          string(5) "mkdir"
                        }
                      }
                      ["imageUploadDir"]=>
                      array(3) {
                        [0]=>
                        string(12) "setting-path"
                        [1]=>
                        NULL
                        [2]=>
                        array(1) {
                          [0]=>
                          string(5) "mkdir"
                        }
                      }
                      ["uploadDir"]=>
                      array(3) {
                        [0]=>
                        string(12) "setting-path"
                        [1]=>
                        NULL
                        [2]=>
                        array(2) {
                          [0]=>
                          string(5) "mkdir"
                          [1]=>
                          string(8) "restrict"
                        }
                      }
                      ["customCSSURL"]=>
                      array(3) {
                        [0]=>
                        string(11) "setting-url"
                        [1]=>
                        NULL
                        [2]=>
                        array(1) {
                          [0]=>
                          string(7) "noslash"
                        }
                      }
                      ["extensionsURL"]=>
                      array(1) {
                        [0]=>
                        string(11) "setting-url"
                      }
                      ["imageUploadURL"]=>
                      array(1) {
                        [0]=>
                        string(11) "setting-url"
                      }
                      ["resourceBase"]=>
                      array(3) {
                        [0]=>
                        string(11) "setting-url"
                        [1]=>
                        string(24) "userFrameworkResourceURL"
                        [2]=>
                        array(1) {
                          [0]=>
                          string(3) "rel"
                        }
                      }
                      ["userFrameworkResourceURL"]=>
                      array(1) {
                        [0]=>
                        string(11) "setting-url"
                      }
                      ["geocodeMethod"]=>
                      array(3) {
                        [0]=>
                        string(8) "callback"
                        [1]=>
                        string(17) "CRM_Utils_Geocode"
                        [2]=>
                        string(16) "getProviderClass"
                      }
                      ["defaultCurrencySymbol"]=>
                      array(3) {
                        [0]=>
                        string(8) "callback"
                        [1]=>
                        string(20) "CRM_Core_BAO_Country"
                        [2]=>
                        string(24) "getDefaultCurrencySymbol"
                      }
                    }
                    ["locals":"CRM_Core_Config_MagicMerge":private]=>
                    NULL
                    ["settings":"CRM_Core_Config_MagicMerge":private]=>
                    object(Civi\Core\SettingsBag)#1954 (6) {
                      ["domainId":protected]=>
                      int(1)
                      ["contactId":protected]=>
                      NULL
                      ["defaults":protected]=>
                      array(165) {
                        ["address_standardization_provider"]=>
                        NULL
                        ["address_standardization_userid"]=>
                        NULL
                        ["address_standardization_url"]=>
                        NULL
                        ["hideCountryMailingLabels"]=>
                        int(0)
                        ["tag_unconfirmed"]=>
                        string(11) "Unconfirmed"
                        ["petition_contacts"]=>
                        string(17) "Petition Contacts"
                        ["civicaseRedactActivityEmail"]=>
                        string(7) "default"
                        ["civicaseAllowMultipleClients"]=>
                        string(7) "default"
                        ["civicaseNaturalActivityTypeSort"]=>
                        string(7) "default"
                        ["civicaseActivityRevisions"]=>
                        bool(false)
                        ["cvv_backoffice_required"]=>
                        string(1) "1"
                        ["contribution_invoice_settings"]=>
                        array(7) {
                          ["invoice_prefix"]=>
                          string(4) "INV_"
                          ["credit_notes_prefix"]=>
                          string(3) "CN_"
                          ["due_date"]=>
                          string(2) "10"
                          ["due_date_period"]=>
                          string(4) "days"
                          ["notes"]=>
                          string(0) ""
                          ["tax_term"]=>
                          string(9) "Sales Tax"
                          ["tax_display_settings"]=>
                          string(9) "Inclusive"
                        }
                        ["invoicing"]=>
                        int(0)
                        ["acl_financial_type"]=>
                        int(0)
                        ["deferred_revenue_enabled"]=>
                        int(0)
                        ["default_invoice_page"]=>
                        NULL
                        ["always_post_to_accounts_receivable"]=>
                        int(0)
                        ["update_contribution_on_membership_type_change"]=>
                        int(0)
                        ["contact_view_options"]=>
                        string(28) "123456789101113"
                        ["contact_edit_options"]=>
                        string(37) "123456789111214151617"
                        ["advanced_search_options"]=>
                        string(46) "123456789101112131516171819"
                        ["user_dashboard_options"]=>
                        string(15) "1234578"
                        ["address_options"]=>
                        string(23) "123456891011"
                        ["address_format"]=>
                        string(231) "{contact.address_name}
{contact.street_address}`

**Comment by twomice** [comment]
Fixed in v1.5.
