### ISSUE TITLE
5.x compatibility

### ISSUE THREAD

**Issue by marsh-circle** [twomice/com.joineryhq.activityical#26]
Hi - nice app! :),
it doesn't list as 5.x compatible though - will it be ok to install on Civi 5.x?

**Comment by twomice** [comment]
Yes, it should be fine. Would you mind trying it and reporting back in this ticket? Based on your findings, we could update the compatibility notes in the extension.

**Comment by marsh-circle** [comment]
sure.
thanks @twomice.

**Comment by twomice** [comment]
Cleaning up old tickets. Closing. This extension is known to be running well on multiple 5.x sites.
