### ISSUE TITLE
Broken URL and Details links

### ISSUE THREAD

**Issue by jarmstrongbts** [twomice/com.joineryhq.activityical#27]
Hi, We also love this extension, it's been a lifesaver for us. We've recently encountered an issue: 

We recently updated our WordPress site to 5.0.3 as well as Civi 5.9.1 and Activity iCalendar Feed 1.5. We're running PHP version 7.1 

Since the update, we cannot access Administer > System Settings > Activity iCalendar Feed (instead the link goes to the Administer CiviCRM page)
There is no longer a link to the Calendar URL on the Contact Activities page.
The Feed and Details links do not work (They both go to the Contact Dashboard, but our website header is at the top, the Civi menu disappears, as does the left WordPress menu. 
Our Google Calendar appears to have stopped updating. (This may be unrelated, but it's been 48 hours since we made a particular update for an activity on Civi and it's not showing in our Google Calendar. 

Wondering if anyone else is experiencing this?

**Comment by twomice** [comment]
Sorry to hear you're having trouble. I haven't heard of others with the exact problems you describe.

However i have seen an issue with CiviCRM extensions in which they lose their settings (i.e., the contents of a "settings" page for the extension, which in this case would be Administer > System Settings > Activity iCalendar Feed). In that issue, the settings page either doesn't appear at all, or it appears as an empty page with only a title and no settings fields. 

I've not seen anyone reporting an actual cause for that issue, but the workaround has been to use CiviCRM's "clear caches" function at _Administer > System Settings > Cleanup Caches and Update Paths_ . This has the effect of rebuilding CiviCRM's list of settings, which will cause it to become aware once again of the extension's settings. Unfortunately, this workaround doesn't restore the values of the settings, so they'll all be blank at this point and will need to be defined and saved in the extension settings page.

If you decide to try the above workaround, please let me know if and how it affects the issue you describe in this ticket.

Thanks,
Allen

**Comment by jarmstrongbts** [comment]
Wow, thanks so much for the quick reply. Just cleaned up the cache and reset URLS and it's working again. I had just done that in the process of updating Civi; it didn't even occur to me that it might be an issue. Thanks again!

**Comment by twomice** [comment]
Glad to hear it. Thanks @jarmstrongbts !

**Comment by twomice** [comment]
Note for posterity: I'm looking for answers on this issue, here: https://civicrm.stackexchange.com/questions/28467/extension-settings-lost-on-upgrade-known-issue
