### ISSUE TITLE
Does not work with version 5.51.1 anymore?

### ISSUE THREAD

**Issue by mariav0** [twomice/com.joineryhq.activityical#46]
I have noticed that it is still working on another instance with version 5.49.4.

On 5.49.4 it looks like this:

![image](https://user-images.githubusercontent.com/70949178/191789252-02f9931a-69b1-4e1e-bbc6-a6e3e50437dc.png)

On 5.51.1:

![image](https://user-images.githubusercontent.com/70949178/191789389-59cf5bb6-b06a-4388-98e2-7f160c98cbd9.png)

It does not show any activities anymore for the contact where this feature is enabled (limited to a group).
For all other contacts I can still see all the activities.
The configuration looks the same.
Release 1.7 is installed and I also tried the master.

When I deactivate the extension I can see all my activities again.

Does anyone else has this problem?

**Comment by twomice** [comment]
I'm not seeing this bad behavior with master or v1.7 under civicrm 5.51.1. Here's a screenshot of what I'm seeing:

![5 51 1](https://user-images.githubusercontent.com/759449/191987789-c8c7066b-9c26-42a7-88bc-0e8109188780.png)

Some questions that might help us figure this out:
1. What CMS and version are you running?
2. What errors, if any, do you see in the browser console (e.g. for Chrome https://developer.chrome.com/docs/devtools/console/)
3. Can you provide the full list of CiviCRM extensions currently enabled on this site? (And, do you still see this bad behavior when all other extensions are disabled?)

**Comment by mariav0** [comment]
Thank you for your quick response!
I've just updated on 1.8 to try if the newest version works and it does.
So I guess we don't need to dive deeper into this issue.

**Comment by mariav0** [comment]
Hi again,
We have tested further and noticed that the URL does not show any entries when adding it to the calender.
The configuration should be correct and there are also activites which should be shown.
What could be the problem?
Do you have any ideas, @twomice ?
Thank you in advance.

**Comment by twomice** [comment]
Hi @mariav0 . No ideas off the top of my head. Since this is something of a separate issue ("activities tab content is missing" vs "actiivities missing from feed URL content"), could I ask you please to submit a separate issue about this, and if possible include specific steps that I could take to try and reproduce your issue? (E.g., 1. Log in; 2. Install the extension ... etc.)
