### ISSUE TITLE
Times are in system time, but timezone is not marked, so time interpretation is unpredictable

### ISSUE THREAD

**Issue by twomice** [twomice/com.joineryhq.activityical#5]
Drupal user jmcclelland writes:

> The [time zone issue](https://www.drupal.org/node/1679160) has been mostly resolved... however, not fully. It seems that now all dates and times are published in the correct UTC date/time. However, they are not labeled as UTC in the feed itself, so when I import the ical feed into Thunderbird's Lightning, the UTC times are displayed as if they are my local time.
> 
> Since I am 5 hours ahead of UTC, all of my events are 5 hours off.
> 
> [It seems that we need to add a Z](http://www.kanzaki.com/docs/ical/dateTime.html) to the end of the date/times.
> 
> This module depends on the core CiviCRM function to parse a date/time into ical format, which is reasonable. But CiviCRM core doesn't make any attempts at timezones either. However, CiviCRM's ical implementation publishes the date/times in the site's time zone, so if you are in the same timezone it seems to be right.

Source: https://www.drupal.org/node/2829802 (which contains a suggested patch)

**Comment by ogomez78** [comment]
Hi @twomice, I forked this wonderful project to fix the timezone issue for Drupal: https://github.com/ogomez78/com.joineryhq.activityical, please take a look. 

Thanks for your work on this. I just used it on a project and it works great.

**Comment by twomice** [comment]
I'm glad to hear that, @ogomez78, and that you have fixes that work for Drupal. I may lean on your Drupal fixes, but also want to make sure the timezones work reasonably for other CMSs as well.  Thanks!

**Comment by ogomez78** [comment]
Great. The changes to Feed.tpl should already be CMS-independent, but the added INNER JOIN on Feed.php isn't, because we needed to hunt for the timezone on the CMS user record. One ideal scenario would be if the timezone was a value on the civicrm_uf_match table. If that was the case, then the INNER JOIN on Feed.php would also be CMS-independent. It should come in handy for other extensions, so it makes sense to make it part of Core.

Thanks again for the great extension!

**Comment by twomice** [comment]
There are a couple of different ways to handle timezones in iCalendar, and the most universally supported seems to be: converting each time to UTC and appending the 'Z' timezone indicator.  I've taken this approach here, and added timezone detection in Drupal, WordPress, and Joomla. In WordPress, the site-wide timezone is used; in Drupal and Joomla, the timezone of the feed contact's CMS user is used if available, and otherwise the site-wide timezone is used. All times are treated as UTC if no timezone can be determined.

**Comment by twomice** [comment]
Thanks to @ogomez78 for beginning the effort to fix this issue. @ogomez78, if you're able to test the patch at https://github.com/twomice/com.joineryhq.activityical/commit/aeb8a3f362e5290cfce9a24acd922ac06fb9d8c1, I'll be grateful for your feedback before merging this in to master.

**Comment by twomice** [comment]
Fixed in b77b9ff1dfd5ba24a8b3e842912380055067489e, which is now in master and will release in version 1.2-beta1
