### ISSUE TITLE
Feed links not displaying under Activities tab (civicrm >= 5.74.4)

### ISSUE THREAD

**Issue by twomice** [twomice/com.joineryhq.activityical#53]
As reported in [a mattermost thread](https://chat.civicrm.org/civicrm/pl/zop36ohhttra7gapiuh7e8rz3r) by @petednz, verified by my and summarized here:

Ext version: 1.9.0
CiviCRM version: 5.74.4 (_possibly_ earlier versions; _probaly_ later ones)

**Repro:**

1. Install and configure the extension so that a given contact (e.g. "Bob Cratchit") should have a working icalendar feed.
2. Confirm that Cratchit has a working feed by navigating to the contact's Contact Dashboard (e.g. example.org/civicrm/user/cid=n). This should (and does, in my testing) display a link to Cratchit's feed details:
![dashboard](https://github.com/user-attachments/assets/adab717d-8480-4b5f-a790-d00f2dd2405f)

3. Navigate to Cratchit's contact record, and open the Activities tab. Look for a link to feed details near the top of ths tab

**Expected:** Links to feed details _should_ appear here, as in this screenshot:
![tab](https://github.com/user-attachments/assets/05044f74-7056-4a29-a59d-fafb3cf32f52)

**Actual:** The links do not appear, as in this screenshot:
![tab-bad](https://github.com/user-attachments/assets/1bc1aec4-b4ea-4e9b-8bc5-e21cf2345d3b)

**Assessment:**
Looks like a bug to me. Extension is making some assumptions that are incompatible with this (and probably future) core versions.

**Comment by twomice** [comment]
@petednz: There's a PR for this in #54 . Would you mind trying that and let me know your findings?

**Comment by petednz** [comment]
Site is using Drupal 10.2.x
Civi was 4.74.4
php 8.1.28

will get it updated for both Drupa and civi and try again

**Comment by twomice** [comment]
@petednz Thanks for the versions. 

I'm really not sure yet what the problem could be, as I'm unable to reproduce.

Repro attempt:

1. Ensure php version is: 8.1.29 
1. Install new and clean Drupal, version 10.2.10
2. Install new and clean civicrm (with sample data), version 5.74.4
3. Place code files for activityical (at commit 8d2173db67934a306191a94cc2a2a3637cbaef95) under `web/sites/default/files/civicrm/ext/` and enable the extension.
4. Log in as admin (user 1)
5. Visit "CiviCRM Activities iCalendar Feed: Settings" ([example.local]/civicrm/admin/activityical/settings); set "Activity iCalendar Feed Group" to "Administrators" only; define no other settings; save the settings.
6. Add contact 'admin@example.com' to the 'Administrators' group
7. Navigate to the Activities tab for this contact.
8. Observe ical links do appear properly; screenshot:  
![act](https://github.com/user-attachments/assets/c155f979-5ca2-441e-908e-35e360d8be6e)


I wonder, maybe some other extension is interfering? Here's my list of installed extensions:
```
11:48 $ cv ext:list -i
Using extension feed "https://civicrm.org/extdir/ver=5.74.4|uf=Drupal8|status=stable|ready=ready"
+----------+-------------------------------------------+---------+-----------+--------+
| location | nameKey                                   | version | status    | extras |
+----------+-------------------------------------------+---------+-----------+--------+
| local    | activityical (com.joineryhq.activityical) | 1.9.0   | installed |        |
| local    | afform (org.civicrm.afform)               | 5.74.4  | installed |        |
| local    | authx                                     | 5.74.4  | installed |        |
| local    | civi_contribute                           | 5.74.4  | installed |        |
| local    | civi_event                                | 5.74.4  | installed |        |
| local    | civi_mail                                 | 5.74.4  | installed |        |
| local    | civi_member                               | 5.74.4  | installed |        |
| local    | civi_report                               | 5.74.4  | installed |        |
| local    | ckeditor4                                 | 5.74.4  | installed |        |
| local    | financialacls                             | 5.74.4  | installed |        |
| local    | flexmailer (org.civicrm.flexmailer)       | 5.74.4  | installed |        |
| local    | greenwich                                 | 5.74.4  | installed |        |
| local    | recaptcha                                 | 5.74.4  | installed |        |
| local    | search_kit (org.civicrm.search_kit)       | 5.74.4  | installed |        |
| local    | sequentialcreditnotes                     | 5.74.4  | installed |        |
+----------+-------------------------------------------+---------+-----------+--------+
```

Things you might try:
- Disable all other extensions; any change?
- Does the contact dashboard display the expected ical info for this contact?
- If you open the Activities tab in a new browser window/tab (e.g. right click on the tab  and choose 'open in new tab'), do the links appear there?
- If you log in as User 1 or other "has all permissions" user, does that change the results? **(I've just realized this may be relevant: these links will display on the Activities tab only if a) the current user is the viewed contact; OR b) the current user has 'administer CiviCRM' permission; this may be an aspect of the design that merits discussion/improvement.)**

**Comment by petednz** [comment]
Client drifted off on another priority. sounds like it is all working as expected. on their site i did disable a couple of likely culprits and changed theme but still nada so will close this. sorry to trouble ya.

**Comment by twomice** [comment]
Yep, that happens (priorities shift). I'm happy to help further with this  if it comes around again. Probably will suggest to start with my last points in my [most recent comment](https://github.com/twomice/com.joineryhq.activityical/issues/53#issuecomment-2435826624). 

For now, though (and for the sake of others reading this): I'm thinking this problem is caused by something specific to the site configuration, and not a bug in the extension. I'll remove the "bug" label from this issue. 

Pete, let me know if/when you want my input on exploring this further. Thanks!
